-
  name: Installing Nginx
  hosts: all
  become: yes
  tasks:
    - name: Nginx
      apt:
        name: nginx
        state: latest

    - name: Start Ngins
      service:
        name: nginx
        state: started
