-
  name: Configure site
  hosts: prd
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: Deploy web page
      copy:
        src: index.html
        dest: /var/www/html
